using CommunityToolkit.Mvvm.Input;
using WindowsSudoku2026.Core.ViewModels;
using WindowsSudoku2026.Services;

namespace WindowsSudoku2026.ViewModels;

public partial class PlayMenuViewModel : ViewModel
{
    INavigationService _navigationService;
    public PlayMenuViewModel(INavigationService navigationService)
    {
        _navigationService = navigationService;
    }
    [RelayCommand]
    private void GoToAutoGeneratedPuzzles() => _navigationService.NavigateTo<PlayViewModel>();
    [RelayCommand]
    private void GoToCustomPuzzles() => _navigationService.NavigateTo<PuzzleSelectionViewModel>();
    [RelayCommand]
    private void GoBack() => _navigationService.GoBack();
}
